name: Deploy to Debian Server

on:
  push:
    branches:
      - rewrite  # or your default branch name

env:
  PROD: true
  DEBUG: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ${{ vars.PROJECT_DIR }}
          git pull origin rewrite
          source .venv/bin/activate
          aerich migrate
          aerich upgrade
          git submodule update --init --recursive --remote
          pip install -U pip
          pip install -r requirements.txt
          systemctl restart --user ${{ vars.SERVICE_NAME }}
